### PR TITLE
Chore/fix login test

### PR DESCRIPTION
**Pull request by YangXingHao96**
## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

### CODE REVIEW

**Comment by AikoPath** [comment]
Hi @YangXingHao96,

We usually try give some context around the chagnes in the PR description you can see above. E.g. what this PR does, why it's needed, how that is achieved, etc. You can have a look at previous PRs from the team to get an idea about it.

This helps the reviewers better understand what the PR is about and nicely documents the changes we do to the codebase for future reference.

In this case for example, I do not know what this is about and can't help much with approving this or offering any other feedback.

**Comment by YangXingHao96** [comment]
@AikoPath, Hi Aiko let me give some context of the pr, if we try to run npm run test:e2e locally we will get the following issue:
image
this is because we have import from @playwright and playwright and if we try to run locally error would be shown, to remove one of the import

**Comment by AikoPath** [comment]
> @AikoPath, Hi Aiko let me give some context of the pr, if we try to run npm run test:e2e locally we will get the following issue: image this is because we have import from @playwright and playwright and if we try to run locally error would be shown, to remove one of the import

Cool, thanks for the context!
As mentioned, it would help to have this kind of information in the description field above.

**Comment by gweiying** [comment]
replaced by #225, closing this~

**Pull request closed without merging**
