### PR TITLE
chore: fix newline display issue in unlock instruction

### PR DESCRIPTION
**Pull request by YangXingHao96**
## Context

_Why does this PR exist? What problem are you trying to solve? What issue does this close?_
Current unlock instruction do not display new line. Adding a css styling to the instruction field will solve this issue
Closes [insert issue #]

## Approach

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

## Risks

_Describes potential risks with this PR. Consider carefully what could possibly happen in a worse case scenario. If possible, try to define risks as 2 items: **Impact** and **Likelihood** and use your best judgment._

### CODE REVIEW

**Comment by PikkaPikkachu** [comment]
Change LGTM, can we also please have some test screenshots for the change @YangXingHao96 ? Thanks!

**Comment by YangXingHao96** [comment]
> Change LGTM, can we also please have some test screenshots for the change @YangXingHao96 ? Thanks!
I will attach some screen shots in the notion project management page

**Comment by YangXingHao96** [comment]
refer to the notion page: https://www.notion.so/opengov/2ccadbea5c734aa09614b4ca8cc7177e?v=76cff9fca57b496f857c990e2639af2f&p=06eddb10729546fd8c379534222ce8a1&pm=s
to see the screenshot of the change

**Review by gweiying — APPROVED** [review]
lgtm! 

Haha in agreement with @PikkaPikkachu on this though, is it ok if we put the screenshots in the PR in the future? Would make reviewing PRs & looking back on past PRs easier.

**Pull request merged**
